### ISSUE TITLE
`validateSchema.form()` validates only `data.$set` in `patch()` hooks

### ISSUE THREAD

**Issue by sokki** [eddyystop/feathers-hooks-validate-joi#1]
If I do `.patch(id, { field: value })`, the validation don't work because it uses `utils.get` from the deprecated package `feathers-hooks-utils` wich looks for data in `data.$set`.

If I do `.patch(id, { $set: { field: value } })` it feels like wrong REST and e.g. `auth.hashPassword()` dont work because it only hashes passwords in `data.password`.

I now use `.patch(id, { $set: fields, …fields })` which is awkward but works in my case.

**Comment by eddyystop** [comment]
Fixed in v1.0.0. Data in `hook.data` is now validated rather than data in `hook.data.$set`. You will have to reinstall `feathers-hooks-validate-joi` in your project.

Feathers will introduce one or more validators into core some time after the new Auk release of Feathers. I will wait until then to see how to handle both `hook.data` and `hook.data.$set`.

**Comment by sokki** [comment]
Awesome. Thanks for the quick fix 🚀 
btw: you forgot 2 console.logs :)
https://github.com/eddyystop/feathers-hooks-validate-joi/commit/b9a0d2aa6ad20d36490de07b7423a87fe17a342a#diff-168726dbe96b3ce427e7fedce31bb0bcR10

**Comment by eddyystop** [comment]
Thanks for the console.log catch. Fixed in 1.0.1.
